Debug BDS segfault #253
Rblp/Rblpapi pull request #346
Opened 2021-12-02 08:33 UTC by klin333

Debugging and potential fix of BDS crashes from #253

Added a bds_debug function to send thousands of bds requests in rapid succession. This helps reliably and quickly reproduce the error. See also tinytests/test_segfault.R

My hunch is that unprotected SEXP in bds.cpp get destroyed by garbage collection. After changing SEXP to Rcpp::RObject throughout bds.cpp, I could no longer reproduce the error. However, I do not have sufficient theoretical knowledge of SEXP to know for sure.

2021-12-02 13:17 UTC, eddelbuettel commented
Besides switching to `RObject`, we could also wrap `Shield<>` or `Protect<>` around the `SEXP` to have a more minimal change.  Otherwise concur.

2021-12-02 13:25 UTC, eddelbuettel commented
Could you, if you have another minute or two, maybe try replacing the `SEXP foo` uses and assignments with `Rcpp::Shield<SEXP> foo` throughout?   That is done more commonly.

(`RObject` is / was good too. At one point it was the top of our object hierarchy but things got moved around. It is not that widely used / idiomatic Rcpp use these days.  Mostly stylistic though.  You put your needle on the issue.)

2021-12-02 22:32 UTC, klin333 commented
Might need some assistance with Shield, getting compiler errors everywhere, to the point where the only way for me to compile is to have no Shield and be back to where we began. 

Something like ```Rcpp::Shield<SEXP> foo;``` doesn't even compile with ```no matching function for call to 'Rcpp::Shield<SEXPREC*>::Shield()'```. I have very minimal knowledge about templates to figure this out... 

Also note that an earlier commit 7f3531d3 deliberately moved away from Shield.

2021-12-02 23:15 UTC, eddelbuettel commented
I concur. I just gave it a spin on a checkout of your branch and that is a fight not worth fighting.  Switching to RObject is a net improvement, and you proposed a fine PR.  I say we go with it.

2021-12-02 23:15 UTC, eddelbuettel commented on R/RcppExports.R
> +bds_Impl_Debug <- function(con_, securities, field, options_, overrides_, repeats, verbose, identity_) {
As a PR to master, this is not needed.  Can you remove the function, and run `compileAttributes()` again to remove it here?

2021-12-02 23:18 UTC, eddelbuettel requested changes

2021-12-02 23:18 UTC, eddelbuettel commented on R/bds.R
> +bds_debug <- function(security, field, options=NULL,
As above, I suggest to remove.  Keep the branch if you will or a copy but we do not this merged.

2021-12-02 23:18 UTC, eddelbuettel commented on inst/tinytest/test_segfault.R
> +print(length(res))
We need to either remove the test file (my suggestion) or condition it similar to the others.  Code can not simply access Blp, sadly.

2021-12-02 23:18 UTC, eddelbuettel commented on src/RcppExports.cpp
> +Rcpp::List bds_Impl_Debug(SEXP con_, std::vector<std::string> securities, std::string field, SEXP options_, SEXP overrides_, int repeats, bool verbose, SEXP identity_);
As above, delete and regenerate so this goes away.

2021-12-02 23:18 UTC, eddelbuettel commented on src/bds.cpp
> +Rcpp::List bds_Impl_Debug(SEXP con_, std::vector<std::string> securities,
As above, please remove and rerun `compileAttributes()`.

2021-12-02 23:26 UTC, klin333 commented
Would it be easier if I make a new fork and just git cherry-pick that 1 commit which actually did the fix? Ie remove the bds_debug commit and remove the tinytest commit.

Eg https://github.com/klin333/Rblpapi/tree/bds_segfault

It looks like if I do that, i'll make a new pull request with the new branch which just has the single commit

2021-12-02 23:30 UTC, eddelbuettel commented
Sure. 

(Random idea:  hard reset three commits back then just cherry pick the one commit in.  No idea if that works.)

Throwing it away and doing a clean PR is easiest. There are worse things than a closed PR.  (If you are redoing things please look at ChangeLog and pretty-please consider adding an entry with name and email.)

2021-12-02 23:47 UTC, klin333 commented
ok, redone as new pull request with just the fix, and ChangeLog entry.

2021-12-03 01:01 UTC, eddelbuettel commented
So I guess we should / can close this one.

2021-12-03 01:01 UTC, closed without merging